### ISSUE TITLE
Expose annotated packages as mutable list?

### ISSUE THREAD

**Issue by JakeWharton** [tbroyer/gradle-nullaway-plugin#1]
Right now I do
```groovy
annotatedPackages.add('com.example')
```
but it seems more common and DSL-y for Gradle in Groovy to do
```groovy
annotatedPackages += 'com.example'
```
and/or
```groovy
annotatedPackages += [ 'com.example.foo', 'com.example.bar' ]
```

**Comment by tbroyer** [comment]
The `ListProperty` allows, among other things, linking the property on the task-level extension to the project-level extension (without using private/deprecated Gradle APIs).

Gradle [does some bytecode manipulation](https://docs.gradle.org/current/userguide/lazy_configuration.html) (or however it's done) to generate setters, allowing setting those `Property` properties using `=` rather than `.set()` in the Groovy DSL, so you'd want to ask them to possibly add Groovy extensions to `ListProperty` (or `HasMultipleValues`) to allow using the `<<` and `+=` operators (same could be done for Kotlin too btw).

---

Fwiw, I'll probably be migrating the `net.ltgt.errorprone` plugin to use lazy properties too, this will allow things like:
```kotlin
tasks.withType<JavaCompile>().configureEach {
    options.errorprone.nullaway.severity.set(options.errorprone.isCompilingTestOnlyCode.map {
        if (it) CheckSeverity.INFO else CheckSeverity.ERROR
    })
}
```
to assign a severity depending whether this is test code or main code, independently of initialization order of that `isCompilingTestOnlyCode` property, so e.g. without the need for `afterEvaluate` in an Android project.
