### ISSUE TITLE
Add DSL for honoring asserts

### ISSUE THREAD

**Issue by JakeWharton** [tbroyer/gradle-nullaway-plugin#2]
https://github.com/uber/NullAway/blob/4f5cc7a21ae0ac9ccb161b9fc013dd83bafb8567/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L42

**Comment by tbroyer** [comment]
It's in v0.2 already actually (https://github.com/tbroyer/gradle-nullaway-plugin/blob/v0.2/src/main/kotlin/net/ltgt/gradle/nullaway/NullAwayOptions.kt#L33), though it looks like I forgot to document it in the README.

**Comment by tbroyer** [comment]
Fixed in 1babda7

Note that, looking back at the code, I'll soon rename the `is`-prefixed properties:
 * `isAssertsEnabled` and `isExhaustiveOverride` will lose their `is` prefix in the Groovy DSL (but still have it with the Kotlin DSL)
 * `isSuppressSuggestions` will be renamed to `suppressSuggestions` (both Groovy DSL and Kotlin DSL).

So if you use `isAssertsEnabled` with the Groovy DSL in v0.2, be prepared for a breaking change in the upcoming v0.3.

**Comment by JakeWharton** [comment]
Yep I was super lazy and only checked the README (and am using Groovy so didn't get autocomplete). Thanks!

**Comment by JakeWharton** [comment]
Hmm can't seem to make this work in the Groovy DSL with 0.2 actually. Tried `isAssertsEnabled = true`, `isAssertsEnabled = Boolean.TRUE`, `isAssertsEnabled.set(true)`, and `assertsEnabled = true`. Everything throws unknown property exception.

**Comment by tbroyer** [comment]
:sob: 

Will have to add a proper test using the Groovy DSL then, like I did in the errorprone plugin (https://github.com/tbroyer/gradle-errorprone-plugin/commit/39e83506bb9fda7a78cc983be7970cc218c6bb5c)

**Comment by tbroyer** [comment]
With 0.2, that should work with `isAssertsEnabled().set(true)`

**Comment by JakeWharton** [comment]
Yep, that works. Thanks!

https://github.com/JakeWharton/dagger-reflect/pull/123

**Comment by tbroyer** [comment]
Fwiw, I just released v0.3 with the breaking changes.
